name: Build apk

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - uses: sparkfabrik/android-build-action@v1.3.4
        with:
          project-path: .
          output-path: my-app.apk
